# Generated by Django 5.0.6 on 2024-06-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rentgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentgame',
            name='game',
        ),
        migrations.AddField(
            model_name='rentgame',
            name='game',
            field=models.ManyToManyField(to='games.game'),
        ),
    ]
